# Generated by Django 4.2.3 on 2023-07-06 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files')),
            ],
        ),
        migrations.CreateModel(
            name='myfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=29)),
                ('domain', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=10)),
                ('area', models.CharField(max_length=500)),
            ],
        ),
    ]
